### ISSUE TITLE
Store session token in message creation

### ISSUE THREAD

**Issue by eselkin** [hackla-engage/engage-backend#106]
Store session token so that when user comments once, the backend knows not to require that user to send emails. We can also NOT require that user to verify the reCaptchas repeatedly that way as well.

**Comment by TeddyCr** [comment]
@eselkin is that to prevent email confirmation for each agenda item submission?

---
cc @owenjoseph

**Comment by TeddyCr** [comment]
Closing issue as this was marked as done
