### ISSUE TITLE
Proposed enhancements to Report PDF Format

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-backend#114]
Following feedback should be considered enhancement / non-MVP for the time being, but pending feedback from City Clerk we may want to peel some of these features off and tag them for MVP.

### Summary of Proposed Enhancements
- Header with City and Council Meeting Date
- Footer with total page count of report
- Layout and Copy suggestions

### Annotated Cover Page

<img width="758" alt="cover page annotated" src="https://user-images.githubusercontent.com/39287217/45647975-1c66a480-ba7c-11e8-901b-1968aabba4c5.png">

### Proposed new Cover Page Layout

[Proposed Report Cover Page [with variable feilds].pdf](https://github.com/hackla-engage/engage-backend/files/2390114/Proposed.Report.Cover.Page.with.variable.feilds.pdf)

### Summary of Proposed Enhancements
- Header and Footer content
    - Page Number and Count
    - Agenda Item
    - City and Date of council meeting
- Summary of Responses (not just comments)
- Other copy and layout suggestions

### Annotated Agenda Item Report page

<img width="726" alt="engage_report_itemfeedback_proposedreadabilityenhancements" src="https://user-images.githubusercontent.com/39287217/45648036-40c28100-ba7c-11e8-9ffe-61a3c391f916.png">

**Comment by owenjoseph** [comment]
@TeddyCr do you know if any of this has been incorporated?

**Comment by eselkin** [comment]
None of that is added... We would have a hard time doing headers and footers.

**Comment by owenjoseph** [comment]
@eliselkin if we want more control over report formatting, does our current library allow for it, or should we open an issue to research alternatives?

**Comment by eselkin** [comment]
There are no PDF alternatives except maybe generating LaTeX and setting up a system to process the LaTex into PDF... I guess that could work

**Comment by owenjoseph** [comment]
We should tag issues like this with "needs research" or something like that.

**Comment by eselkin** [comment]
Actually, the more I think about it, the more that option makes sense using LaTeX for formatting, because it can make headers and footers without a problem since it's a typesetting language

**Comment by eselkin** [comment]
So now there are headers which show which agenda item the comments are for. 
There are page numbers
I'll add # responses, pro con etc. to a little line below the item name. We can add the name of the council meeting to the header for each page, but I think it's a bit of an overkill

**Comment by TeddyCr** [comment]
I am considering this has close with the latest version of the pdf
