### ISSUE TITLE
Are the tags populated?

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-backend#127]
Tags return no results.
```
curl https://backend.engage.town/api/tag/Community/agenda/items?format=json 
curl https://backend.engage.town/api/tag/Sustainability/agenda/items?format=json
```

**Comment by eselkin** [comment]
curl -X GET "https://backend.engage.town/api/tag/Community/agenda/items/" -H "accept: application/json" 
works

**Comment by hungrymonkey** [comment]
I kinda figure the cors thing.
Ok, the url changed a little bit
