### ISSUE TITLE
Set up email notfication to signal scrapping

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-backend#134]
Kaveman suggested, we can register a private email to signal when to run the scraper.
Email should be received after a new agenda item has been added to the website.

This feature can reduce the time between posting and scrapping.

**Comment by eselkin** [comment]
Not very easy and requires integration with new APIs rather than just increasing the frequency of a simple HTTP request. 

Alternative ideas:  changing to monitoring the RSS feed require a cron-like check, either it's to poll the RSS feed or poll the website.

**Comment by TeddyCr** [comment]
@eselkin are you ok with labeling this one as backlog?

**Comment by eselkin** [comment]
I think we can close it since we're not going in that direction.
