### ISSUE TITLE
Missing packages in requirements.txt?

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-backend#137]
Hey guys,

I was trying to run the backend on my local machine and I had to add all the below packages manually to finally be able to run `python3 manage.py`. My virtual environment was activated and I did run `pip install -r requirements.txt`. 

I think we may need to add these to the requirements.txt file. Let me know if that makes sense and I'll go ahead and add them:
* jango_celery_beat
* drf-openapi
* drf-yasg
* django-cors-headers
* djangorestframework
* psycopg2
* html-codec
* googlemaps

**Comment by eselkin** [comment]
Will do right now
