### ISSUE TITLE
Docker Compose build Fail

### ISSUE THREAD

**Issue by kaelancotter** [hackla-engage/engage-backend#144]
Running `docker-compose build` from the latest clean commit currently fails. ( https://github.com/hackla-engage/engage-backend/commit/e39c581b2d9986be8c89ead7e4081be1b9d0f9d6 )  I think this is related to the discrepency between requests versions in the [requirements.txt](https://github.com/hackla-engage/engage-backend/blob/master/requirements.txt#L88) file and the [pipenv](https://github.com/hackla-engage/engage-backend/blob/master/Pipfile#L70) and [pipenv.lock](https://github.com/hackla-engage/engage-backend/blob/master/Pipfile.lock#L966) files.  Is there a reason requests was reverted back to 2,12,1?  Running docker compose against https://github.com/hackla-engage/engage-backend/commit/deac2d7b099d4d029b2849a43b3e7e3de8078f9b builds without error.

**Comment by kaelancotter** [comment]
I'm not sure if its worth it but a new build directive for circleci with the compose stack would be a possibility for testing/prevention  (Might also be a way with pipenv but I'm not too familiar with the tool)

**Comment by eselkin** [comment]
We could have it be a build step... Not sure why that thing happened with requests... it should always be kept up to date.
