### ISSUE TITLE
Add Elasticsearch component and model for search.

### ISSUE THREAD

**Issue by eselkin** [hackla-engage/engage-backend#153]
- [ ] Add API endpoints for elasticsearch
- [ ] Add model for elasticsearch
- [ ] Add elastic search image as component to docker-compose (preferably 6.6.0)
- [ ] Add component of scraping to populate elasticsearch model

**Comment by TeddyCr** [comment]
@eliselkin, to improve the way we track feature development, we are going to track feature on the organization project board. This should allow us to:
- track development progress related to a specific feature more easily
- be able to track what needs to be done across frontend and backend repo

I have created the [search feature](https://github.com/orgs/hackla-engage/projects/3) project board already, and I have started working on translating your above points into individual issues linked to this project. :)

**Comment by eselkin** [comment]
It's very confusing when working on the backend to see content related to the frontend.

**Comment by TeddyCr** [comment]
That makes sense. Let's assign it to both project as you did (the Feature focused one (organization scope) and the backend specific one (repo scope)). We gonna move away from the generic organization project board (still keeping the repo specific one, though), as it is confusing for us to track feature progress.

Can you rename the backend specific project board to something more generic (the MVP is already out, so we need a more generic name to prevent conufsion)

**Comment by TeddyCr** [comment]
These to-dos are all individually referenced in #172 , #174 , #175 (link to [project](https://github.com/orgs/hackla-engage/projects/3))
