### ISSUE TITLE
Move PDF_Reports folder to the static folder

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-backend#154]
## Context
Currently, the generated PDF report is saved in a PDF_Reports folder on the server. To make it readily available to users to download on the client, we need to move this folder to the Django `STATIC_ROOT` folder as a subfolder.

## Task
- [ ] move `PDF_Reports` folder to `static` folder as a subfolder
- [ ] update `writePDF.py` to reference the and save the report to `static/PDF_Reports`

**Comment by eselkin** [comment]
I think adding them to static is a problem... I believe static is parsed at startup and not updated if there are changes. I'll double check this.

**Comment by eselkin** [comment]
Yeah, the only way we can change it is if we use whitenoise as the static files middleware.

**Comment by eselkin** [comment]
Even whitenoise suggests this is a bad use of static files. We will have them in another directory.

**Comment by eselkin** [comment]
static PDFs will be served from https://backend.engage.town/staticpdf/xxxx.pdf using nginx
