### ISSUE TITLE
Future possibilities: scrape rss feeds

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-backend#155]
We can always scrape the rss feed but it takes longer to load.

https://www.smgov.net/departments/clerk/agendas_rss.ashx

https://www.smgov.net/departments/clerk/AgendasRssToHTML.aspx

I will add more information when I manage to finish the parser project.

**Comment by TeddyCr** [comment]
@hungrymonkey @eliselkin, can this be closed? It has been marked as proposal for almost 2 months.

**Comment by eselkin** [comment]
I don't find it a useful thing to look into.
