### ISSUE TITLE
Scraper needs to be refactored into a library.

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-backend#156]
https://github.com/hackla-engage/engage-backend/blob/master/CouncilTag/ingest/utils.py

The scraper seems to push data models as the scraper serializes it.

The scraper needs to be refactor so the parser is a library instead.

   

* what this about?
Trying to write a unit test
* why we need to do it?
Separate side effects from the scraper
* what is the impact of not doing it?
No way to unit test the scraper
* what benefits would it provide for the project overall (for the current municipality and potentially other municipalities)?
We can create an automated unit test framework for the scraper.

**Comment by hungrymonkey** [comment]
I am thinking of changing save -> yield.

**Comment by hungrymonkey** [comment]
It seems like http request is embedded in the code

https://github.com/hackla-engage/engage-backend/blob/master/CouncilTag/ingest/utils.py#L50

Not a good thing.

**Comment by hungrymonkey** [comment]
https://github.com/hackla-engage/engage-backend/blob/master/CouncilTag/ingest/data.py#L88

Another get request embedded.

**Comment by hungrymonkey** [comment]
@dstrodtman @eselkin 

I am thinking of attempting to untangle get request from the serialization code. I am thinking of sprinkling yield instead of another method call.

**Comment by hungrymonkey** [comment]
My changes should be as minimum as possible

**Comment by TeddyCr** [comment]
@hungrymonkey can you give more details, background and context for the team to understand:
- what this about
- why we need to do it
- what is the impact of not doing it
- what benefits would it provide for the project overall (for the current municipality and potentially other municipalities)

----

cc @owenjoseph

**Comment by eselkin** [comment]
> I am thinking of changing save -> yield.

Yield is for generators/iterators saves are required to store the data to the database

**Comment by eselkin** [comment]
> It seems like http request is embedded in the code
> 
> https://github.com/hackla-engage/engage-backend/blob/master/CouncilTag/ingest/utils.py#L50
> 
> Not a good thing.

That get_data is not an http request.

**Comment by eselkin** [comment]
the scraper does need to be an app (not a library) by itself. But we'll have to look at that as a group

**Comment by hungrymonkey** [comment]
@eliselkin 

I am thinking of doing something some simple as
```
request = http.get(url)
for model in scrape_website(request.text):
   model.save()
```
Either way, I need to clean up all the side effects from the scraper.

**Comment by eselkin** [comment]
That's missing the depth of the items

**Comment by TeddyCr** [comment]
@hungrymonkey @eliselkin can this issue be closed? it has been marked as proposed for slightly over a month.

**Comment by eselkin** [comment]
I have no problem closing it.
