### ISSUE TITLE
PyMySQL in requirements.txt

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-backend#158]
https://github.com/hackla-engage/engage-backend/blob/master/requirements.txt#L74

I believe this project uses postgres and redis

https://github.com/hackla-engage/engage-backend/blob/master/CouncilTag/settings.py#L122

Do we need this dep?

**Comment by eselkin** [comment]
It's related to something else that depends on it. I think. Do requirements the graph.

**Comment by hungrymonkey** [comment]
Ok, I will find a tool to list deps
https://github.com/naiquevin/pipdeptree
I might end up putting this issue on the back burner for awhile.

**Comment by kaelancotter** [comment]
pipenv in alredy in the project.  I think `pipenv graph` should show the dependency graph

**Comment by eselkin** [comment]
Yeah, did that, nothing depends on it, so @hungrymonkey you can make a PR to remove it

**Comment by joshbeme** [comment]
https://github.com/hackla-engage/engage-backend/pull/161 
deleted a line on this issue
