### ISSUE TITLE
Add API endpoint for upcoming meeting(s)

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-backend#162]
Dig this comment from engage-client issue 135: https://github.com/hackla-engage/engage-client/issues/135#issuecomment-478267596

I think it would add value if we were to provide the upcoming meeting dates in the "no-active-issues" Splash text, but @joshbeme noted that this data isn't available in our API endpoint. Are we even scraping this data (upcoming city council meeting dates)?

**Comment by eselkin** [comment]
No, we're not scraping any data that doesn't have meeting agendas yet

**Comment by owenjoseph** [comment]
@eliselkin I feel like there's still value to displaying the date of the next upcoming scheduled meeting, even if agenda items for that meeting haven't been posted by the city yet. At the very least I think this kind of messaging would support the Call to Action to sign up to the newsletter – something along the lines of: "The next scheduled city council meeting is [date]. Agenda Items aren't posted yet, but sign up for our newsletter and we'll let you know as soon as they are public."

**Comment by eselkin** [comment]
We'd have to create a separate scraper, some other way to store unscraped agenda dates, etc.

**Comment by owenjoseph** [comment]
Understood. Maybe we can just direct users to the city agendas page for now.

**Comment by hungrymonkey** [comment]
@owenjoseph Now, you understand why we desperately need a way this unit scraper project.

We cannot add more features until we can ensure correct output.

**Comment by eselkin** [comment]
That's completely unrelated

**Comment by TeddyCr** [comment]
Marked this has abandoned for now and closed the issue
