### ISSUE TITLE
Add & Set Up Elasticsearch image to docker-compose

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-backend#172]
### Context
Engage is working on developing a search functionality to improve the UI experience of its user. We'll use elastic search to enable users to narrow down agenda items to a specific topic.
**Interesting link:** [install Elasticsearch on Docker](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)

### File(s)
The docker compose file can be found at the [root of the backend repo](https://github.com/hackla-engage/engage-backend).

### Dependencies
- None

### To Dos
-  [x] Add Elasticsearch image (>=6.6.0) to docker-compose file
-  [x] Create node, and index. We will create 1 index per year per municipality (i.e. Santa_Monica_2019)
  
To confirm our cluster is functional we should get a green (or yellow) status when running the `GET /_cat/health?v` command. 

----
#### New to the Project?
Check out our product [documentation repo](https://github.com/hackla-engage/Product-Documentation).

**Comment by kaelancotter** [comment]
Been looking into this already 6.6.0 iirc

**Comment by kaelancotter** [comment]
Do we want pinned at 6.6.0 or something closer to latest (7.0.1 at this time)?  Also any preference about oss vs standard?

**Comment by kaelancotter** [comment]
https://github.com/kaelancotter/engage-backend/commit/c112c3dae853ab4c779fedc728cbfece396266d6  Is a start at least

**Comment by TeddyCr** [comment]
@kaelancotter / @eliselkin what do you guys think of creating 1 index per year per committee? The idea being that data will be centralized across municipalities (similar to how our RDBSM is managed) in the elastic search cluster but distinguished based on the index.

**Comment by eselkin** [comment]
Indexes are pretty large structural things in elasticsearch... probably having 1 index per committee is best and just adding years to the index. You would need separate endpoints for each index and that's a lot of work/extra stuff for the backend.

**Comment by TeddyCr** [comment]
Make sense. In the proposed document field structure (#174) we put a "date" field.

**Comment by eselkin** [comment]
This way, you can also limit between date ranges rather than having to make multiple calls to different indices.

**Comment by TeddyCr** [comment]
Completed. 
View PR [#3](https://github.com/hackla-engage/engage-docker/pull/3) in engage-docker repor
