### ISSUE TITLE
Successful scrape triggers tweet

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-backend#173]
Each time we successfully scrape new agenda content and post to the feed, we should post a new tweet to the Engage Santa Monica twitter account: @EngageStaMonica

Tweet language should equal: 

Agenda Items for the next @santamonicacity City Council meeting is open for public feedback until 11:59am [Month | Date]. Head to http://sm.engage.town now to voice your opinion!

Month | Date text should be formatted like e.g. "Feb 26th".

**Comment by mostafa-abdo** [comment]
Would using IFTTT, https://ifttt.com/, be a good fit for this task? I believe we would need an rss feed on the site.

**Comment by eselkin** [comment]
There is already an event that happens when a new agenda is scraped. Then use https://github.com/bear/python-twitter

**Comment by TeddyCr** [comment]
@calyao  what is the update on this? Are you still working on it?

**Comment by calyao** [comment]
I'm sorry; I'm not working on it. No updates as a result.

**Comment by eselkin** [comment]
This should actually be in the Celery repo not the backend.
