### ISSUE TITLE
[Feature Request] Query executive summary

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-backend#19]
Would it be possible to grab the "executive summary" from the current site to place on a page in the wire flow being create

http://santamonicacityca.iqm2.com/Citizens/Detail_LegiFile.aspx?Frame=&MeetingID=1134&MediaPosition=&ID=2800&CssClass=

div class="LegiFileSectionContents"

**Comment by eselkin** [comment]
No longer querying executive summary.
