### ISSUE TITLE
spike : automatic email verification

### ISSUE THREAD

**Issue by ricokareem** [hackla-engage/engage-backend#52]
to encourage passive engagement, research how we can do some sort of automatic, low-level, sanity-checking of email addresses. possibly removing the need for the user to respond to a verification email.

format username@domain.com is valid
lookup domain.com does not come back as NSDOMAIN
SMTP response.

**Comment by owenjoseph** [comment]
Hey @ricokareem I'm gonna tag this one with the label "question" - we've got a lot of open research items like this, thought it might make sense to raise their visibility.

**Comment by eselkin** [comment]
Actually, I think this is simple enough to just put in without thinking about having to research more. We can take it out if we decide to go a different route. Why not make a pull request, @ricokareem?

**Comment by owenjoseph** [comment]
Hey @eselkin I was thinking about this feature as a protection (if imperfect) against voting abuse. The importance of verifying a submitter's residence status is an open question still.

**Comment by TeddyCr** [comment]
@ricokareem, for the MVP, a comment will trigger an email verification to be sent to the input email address. While the user has not clicked on the verification link, the comment will be marked as unverified.

**Comment by TeddyCr** [comment]
@ricokareem Adding@iamemilywing comment from #60 (now closed and marked as duplicate):

-----

User should receive an email with a request to confirm email address if they submit and confirm a Position (use the vote form) and do not have a verified email in the system.

User should be linked to a confirmation page. (Issue linked Here)

Sample text:
Please click on the link to verify this email and complete your submission

{{link}}

link to full flow for reference
link to video of flow
https://www.youtube.com/watch?v=crD0EXfXYjc&feature=youtu.be

**Comment by eselkin** [comment]
@TeddyCr, this is not the same as the other issue #60 
This method is a passive method, not the link and integration from #60.
**Reopen #60**
This issue should be closed if we are going with #60 (active user verification is better than passive).
