### ISSUE TITLE
Store user info (name, zip, etc.), comments, and votes per agenda items

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-backend#54]
Connect front end comment form + votes with the database to store user input data.

**Comment by eselkin** [comment]
There is already a storage of comments when the /api/add/message is called

**Comment by TeddyCr** [comment]
Awesome, does it stores all the other information as well:
- First name
- Last name
- Zip Code
- Vote
- etc.

**Comment by eselkin** [comment]
Yes

**Comment by eselkin** [comment]
<img width="212" alt="screen shot 2018-06-21 at 8 30 10 am" src="https://user-images.githubusercontent.com/5606931/41729179-67676c06-752d-11e8-8e19-ed7c0b9e7888.png">

**Comment by TeddyCr** [comment]
Added the Ethnicity models and script to prepopulate values in database.
