### ISSUE TITLE
Agenda Item Report should be compiled  into a PDF at 12:01 PM PST the day of the Meeting and sent to council

### ISSUE THREAD

**Issue by iamemilywing** [hackla-engage/engage-backend#61]
Agenda Item Report should be compiled at 12:01 PM PST the day of the Meeting and sent to council.

Report should be a PDF and go to multiple emails (TBD, leave the ability for multiple).  Report should be sent before 1pm PST the day of meeting.

The report should have
- User email
- Name (if avail_
- Position 
- Comments
- Array of demographic data (if avail)
- Timestamp Posted in PST  (format: Monday, Jun. 26, 2018 at 8:00 AM PST)

Mockup
https://invis.io/AYLW5IAUV5T#/304921727_Email

**Comment by eselkin** [comment]
Would be helpful if someone knew reportlab well! Any takers?

**Comment by TeddyCr** [comment]
@eselkin I'll look into it.

**Comment by TeddyCr** [comment]
@eselkin @owenjoseph, I see a writePDF.py in the ingest app, is this fully completed?

**Comment by TeddyCr** [comment]
@eselkin, cool, I'll take on that one.

**Comment by TeddyCr** [comment]
Pull request has been submitted
