### ISSUE TITLE
System should generate report for all proposals that have received feedback and email them to City Staff after 1200hrs day of Council Meeting

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-backend#62]
After 1200hrs – after system has locked out users from submitting additional feedback - system should aggregate feedback from each proposal which has received feedback into a Report. Each proposal/agenda item should have a separate report.

These reports should be generated as PDFs. Once these PDFs are generated, they should be emailed to councilmtgitems@smgov.net

The subject of the email should be:
"Engage Santa Monica - Aggregated Feedback for [date of council meeting] City Council Meeting Agenda Items"

The body of the email should follow this format:
"
To whom it may concern:

Please find attached PDFs representing aggregated feedback pertaining to the agenda items to be discussed during the City Council meeting scheduled for [date].

Attachment Manifest:
-----------------------

[Item #] | [filename] or, if no feedback ["No Feedback Received; No Report Attached"]
"

**Comment by owenjoseph** [comment]
@iamemilywing could you attach the report mockup you created to this ticket?

**Comment by TeddyCr** [comment]
@owenjoseph looks like this a duplicate of #61 created by @iamemilywing. Would you be able to transfer your comment over there and close this one?

**Comment by owenjoseph** [comment]
Whoops! Thanks @TeddyCr .
