### ISSUE TITLE
Parallelize the scraping 

### ISSUE THREAD

**Issue by eselkin** [hackla-engage/engage-backend#95]
Scraping is slow because you have to scrape each agenda to see if there are new items, but you should be able to scrape agendas simultaneously or make the test to see if the agenda item is already scraped before you actually scrape that agenda item.

**Comment by TeddyCr** [comment]
@eselkin just thinking of seomething regarding this, could Parallelizing the scrapping create a DOS and bring their site down if we send multiple requests at the same time?

**Comment by eselkin** [comment]
I made the scraping much faster in the last iteration, so I don't really think this is that important. But no, it's not a DOS style parallelization. 50 requests or something is not going to trigger that type of result.

**Comment by TeddyCr** [comment]
@eliselkin  Is that still something we want to work on?

**Comment by eselkin** [comment]
I'm not sure. I'll keep it open and we'll consider it later.

**Comment by TeddyCr** [comment]
@eselkin can we close this now that we have [engage-scrapper](https://github.com/hackla-engage/engage-scraper)

**Comment by eselkin** [comment]
Yes, but we should open one there
