### ISSUE TITLE
Do we have a new doc page?

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-backend#98]
https://github.com/hackla-engage/engage-backend/issues/48

I am going to attempt to query save user tags soon.

https://council-tag.herokuapp.com/docs/

Current council-tag.herokuapp.com doesnt document the new end point

**Comment by eselkin** [comment]
I've mentioned this a few times (and it's on this repo's readme)... that is no longer the backend site.
The backend is: https://backend.engage.town
The swagger docs are at: https://backend.engage.town/swagger/

**Comment by eselkin** [comment]
Also querying tags, adding tags is not MVP

**Comment by hungrymonkey** [comment]
ok, thanks. i will update the README
